version: '3.8'

services:
  postgres-central:
    image: postgres:16-alpine
    container_name: postgres-central
    restart: unless-stopped
    environment:
      # Super user credentials
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_PASSWORD:-centralPostgres2024!}
      POSTGRES_DB: postgres
      
      # Performance optimization
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_MAX_CONNECTIONS: 200
      
    volumes:
      # Data persistence
      - postgres_central_data:/var/lib/postgresql/data
      
      # Custom configuration
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      
      # Initialization scripts for all databases
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      
      # Backup directory
      - ./backups:/backups
      
    ports:
      # Exposed for admin tools and external connections
      - "5432:5432"
      
    networks:
      - postgres-network
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
      
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: '0.5'
        reservations:
          memory: 512MB
          cpus: '0.25'
          
    # Security
    security_opt:
      - no-new-privileges:true
    user: postgres
    
# PgAdmin disabilitato temporaneamente per avvio veloce

volumes:
  postgres_central_data:
    driver: local
      
  pgadmin_data:
    driver: local

networks:
  postgres-network:
    driver: bridge
    external: false
    
  traefik-network:
    external: true
